insert into Ingredient (ingredientID, name, portionSize, amountNeeded, quantityAvailable, recipeID) values (4, 'lacus morbi quis', 'Large', 2, 83, 13);
insert into Ingredient (ingredientID, name, portionSize, amountNeeded, quantityAvailable, recipeID) values (1, 'convallis nunc proin at', 'Large', 1, 37, null);
insert into Ingredient (ingredientID, name, portionSize, amountNeeded, quantityAvailable, recipeID) values (2, 'faucibus cursus urna ut', 'Large', 2, 126, 11);
insert into Ingredient (ingredientID, name, portionSize, amountNeeded, quantityAvailable, recipeID) values (1, 'dapibus augue vel accumsan', 'Medium', 5, 97, 14);
insert into Ingredient (ingredientID, name, portionSize, amountNeeded, quantityAvailable, recipeID) values (2, 'felis eu sapien cursus', 'Large', 4, 199, 4);
insert into Ingredient (ingredientID, name, portionSize, amountNeeded, quantityAvailable, recipeID) values (2, 'non velit nec nisi', 'Large', 3, 78, 9);
insert into Ingredient (ingredientID, name, portionSize, amountNeeded, quantityAvailable, recipeID) values (1, 'luctus rutrum nulla', 'Small', 3, 143, 10);
insert into Ingredient (ingredientID, name, portionSize, amountNeeded, quantityAvailable, recipeID) values (2, 'a libero nam', 'Large', 5, 81, 11);
insert into Ingredient (ingredientID, name, portionSize, amountNeeded, quantityAvailable, recipeID) values (2, 'imperdiet sapien urna', 'Large', 1, 159, 14);
insert into Ingredient (ingredientID, name, portionSize, amountNeeded, quantityAvailable, recipeID) values (1, 'nam tristique tortor eu', 'Medium', 1, 17, 14);
insert into Ingredient (ingredientID, name, portionSize, amountNeeded, quantityAvailable, recipeID) values (2, 'bibendum felis sed interdum', 'Large', 5, 94, 10);
insert into Ingredient (ingredientID, name, portionSize, amountNeeded, quantityAvailable, recipeID) values (2, 'nulla suscipit ligula in', 'Large', 4, 120, 13);
insert into Ingredient (ingredientID, name, portionSize, amountNeeded, quantityAvailable, recipeID) values (2, 'ridiculus mus etiam vel', 'Small', 1, 172, 12);
insert into Ingredient (ingredientID, name, portionSize, amountNeeded, quantityAvailable, recipeID) values (4, 'magna bibendum imperdiet', 'Small', 5, 170, 13);
insert into Ingredient (ingredientID, name, portionSize, amountNeeded, quantityAvailable, recipeID) values (2, 'neque libero convallis', 'Large', 1, 172, 2);
insert into Ingredient (ingredientID, name, portionSize, amountNeeded, quantityAvailable, recipeID) values (3, 'ligula in lacus curabitur', 'Small', 1, 133, 6);
insert into Ingredient (ingredientID, name, portionSize, amountNeeded, quantityAvailable, recipeID) values (1, 'donec odio justo sollicitudin', 'Large', 4, 73, 2);
insert into Ingredient (ingredientID, name, portionSize, amountNeeded, quantityAvailable, recipeID) values (4, 'duis bibendum morbi', 'Small', 3, 2, null);
insert into Ingredient (ingredientID, name, portionSize, amountNeeded, quantityAvailable, recipeID) values (2, 'sed tristique in', 'Small', 3, 109, 9);
insert into Ingredient (ingredientID, name, portionSize, amountNeeded, quantityAvailable, recipeID) values (3, 'molestie hendrerit at vulputate', 'Large', 5, 124, 1);
insert into Ingredient (ingredientID, name, portionSize, amountNeeded, quantityAvailable, recipeID) values (3, 'integer non velit', 'Large', 1, 195, 11);
insert into Ingredient (ingredientID, name, portionSize, amountNeeded, quantityAvailable, recipeID) values (3, 'ut nulla sed', 'Large', 5, 191, 8);
insert into Ingredient (ingredientID, name, portionSize, amountNeeded, quantityAvailable, recipeID) values (1, 'id consequat in consequat', 'Small', 1, 107, 4);
insert into Ingredient (ingredientID, name, portionSize, amountNeeded, quantityAvailable, recipeID) values (1, 'eget congue eget semper', 'Medium', 4, 87, 2);
insert into Ingredient (ingredientID, name, portionSize, amountNeeded, quantityAvailable, recipeID) values (2, 'dictumst maecenas ut massa', 'Small', 5, 81, 7);
insert into Ingredient (ingredientID, name, portionSize, amountNeeded, quantityAvailable, recipeID) values (2, 'amet nunc viverra', 'Large', 3, 138, 3);
insert into Ingredient (ingredientID, name, portionSize, amountNeeded, quantityAvailable, recipeID) values (1, 'quam pharetra magna ac', 'Medium', 2, 198, 7);
insert into Ingredient (ingredientID, name, portionSize, amountNeeded, quantityAvailable, recipeID) values (2, 'vitae mattis nibh', 'Small', 3, 136, 10);
insert into Ingredient (ingredientID, name, portionSize, amountNeeded, quantityAvailable, recipeID) values (4, 'vulputate luctus cum', 'Small', 2, 175, 10);
insert into Ingredient (ingredientID, name, portionSize, amountNeeded, quantityAvailable, recipeID) values (3, 'lorem vitae mattis', 'Large', 1, 97, 15);
